#ifndef ROBOT_MAP_H
#define ROBOT_MAP_H

#define LEFT_DRIVE_MOTOR_ID 0
#define LEFT_DRIVE_MOTOR_SLAVE_ID 2
#define RIGHT_DRIVE_MOTOR_ID 1
#define RIGHT_DRIVE_MOTOR_SLAVE_ID 3

#define DRIVE_XMSN_SHIFTER_ID 0

// #define FR_DRIVE_MOTOR_ID 20
// #define BR_DRIVE_MOTOR_ID 21
// #define BL_DRIVE_MOTOR_ID 22
// #define FL_DRIVE_MOTOR_ID 23

// #define FR_STEER_MOTOR_ID 24
// #define BR_STEER_MOTOR_ID 25
// #define BL_STEER_MOTOR_ID 26
// #define FL_STEER_MOTOR_ID 27

#define DRIVER_XBOX_CONTROLLER_ID 0
#define OPERATOR_XBOX_CONTROLLER_ID 1

#endif // ROBOT_MAP_H
