#ifndef ROBOT_MAP_H
#define ROBOT_MAP_H

#define LEFT_DRIVE_MOTOR_ID 0
#define LEFT_DRIVE_MOTOR_SLAVE_ID 2
#define RIGHT_DRIVE_MOTOR_ID 1
#define RIGHT_DRIVE_MOTOR_SLAVE_ID 3

#define DRIVE_XMSN_SHIFTER_ID 0

#define DRIVER_XBOX_CONTROLLER_ID 1
#define OPERATOR_XBOX_CONTROLLER_ID 2

#endif // ROBOT_MAP_H
